version: '2'

services:
  postgres:
    image: 'sameersbn/postgresql:9.6-2'
    ports:
      - "5432:5432"
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
      - PG_PASSWORD
    volumes:
      - persistent:/var/lib/postgresql
volumes:
  persistent:
